spring:
  profiles:
    active: default, native

---

server:
  port: 10081

spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/demo
